# frozen_string_literal: true

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

source "https://rubygems.org"

gem "bundler"
gem "overcommit"
gem "panolint-ruby", git: "https://github.com/panorama-ed/panolint-ruby.git",
                     branch: "main"
